neovim/node-client

README.mkd

Saving it to a particular project would make meaningless copies of the client code (unless the user uses the `link` option`). This allows one copy to be used everywhere.

Recommend to install client globally.

---

index.js

Fixes #8. 
`obj` holds some state for subsequent requests including the msgpack5 `BufferList` that should only contain `Buffer` objects. This function was replacing the contents of the buffer list with strings.

Don't traverse into _session when decoding

---

index.d.ts
index.js

Fixes https://github.com/neovim/node-host/issues/13
Defines  `attach`, `detach`, and `tryResize` on the `Nvim` type.  This is consistent with the [python client](https://github.com/neovim/python-client/blob/master/neovim/api/nvim.py#L172).  Also, the auto-generated methods are aliased to their old names to keep backwards compatibility.
I'm just getting started in neovim plugins, so please use a critical eye in reviewing the PR; the tests don't seem to cover a change like this.  I did try copying these changes into my install of the `node-host`, and it did fix the error with `UpdateRemotePlugins`.

Correctly define ui_* methods from neovim api info.

---

generate-typescript-interfaces.js
index.d.ts

This is convenient e.g. if you're writing a plugin with the [node-host](https://github.com/neovim/node-host) and want to have types for the client passed to your commands, functions, etc.

Export Generated Interfaces

---

generate-typescript-interfaces.js
index.d.ts
index.js

Previously, `attach()` was exported as _whole_ of the package.  However, `index.d.ts` says that it is exported as _default_ of package.  _whole_ and _default_ is not the same thing in ES2015 and TypeScript, they are always confusing:
```javascript
// Whole import
import * as attach from 'neovim-client';
// Default import
import attach from 'neovim-client';
```
In general, people prefers default export because it's much more generic.  So I exported `attach()` also as a 'default' of this package.

Export attach() also as a default

---

Makefile
generate-typescript-interfaces.js
index.d.ts
package.json
test/typescript-test.ts

I added a test for TypeScript type definitions and integrated it into CI.
And I fixed some broken points in `index.d.ts`
- `declare module` should not be used for type definitions resolved as npm package
- `Nvim` should inherit `EventEmitter`
- Add missing `equals()` methods

Fix broken TypeScript type definition and introduce test 

---

.travis.yml

Currently Node.js has two primary branches:
- stable: latest stable release
- LTS: long-term supported release
I think specifying them is better than specifying versions directly. We no longer need to take care about Node.js versions on Travis CI.

Use 'stable' and 'lts/*' to reduce maintain cost for Travis CI

---

package.json

If my understanding is correct, TypeScript is only used in development environment. So I moved the package from `dependencies` to `devDependencies` to reduce runtime dependencies.

Move typescript package to devlopment dependency

---

src/api/Neovim.ts

The typing for atomic call should be any[].

Updated typings for atomic call

---

.npmrc
__tests__/integration/autoload/provider/node.vim
__tests__/integration/rplugin/node/test/package.json
package.json

I added tiny fixes:
- Avoid creating `package-lock.json` by putting `.npmrc`
- Remove unused script in test plugin
- I noticed that test hung when `neovim-node-host` command was not found. I fixed it by adding check in `autoload/provider/node.vim`
- Because all compilation errors are gone, compilation errors should now be respected

Tiny fixes

---

.travis.yml

I added Gitter integration for Travis CI because we moved to Travis CI at #39 
c.f https://docs.travis-ci.com/user/notifications/#Configuring-webhook-notifications

Notify CI status to Gitter

---

.travis.yml

Debug CI issues caused by https://github.com/neovim/neovim/pull/7734, https://github.com/neovim/neovim/pull/7738, and any issues with the latest stable version of nodejs

Fix integration tests on Travis

---

.appveyor.yml
README.md
package.json
src/api/Neovim.test.ts

I tried to setup AppVeyor. I wrote an AppVeyor config and a script to download nightly Neovim package. Now tests look to be run correctly.
But I have seen some test failures for node-host.
~~Since I'm not an node-host user, I could not fix the failures. Can anyone help me?~~
It seems that Travis CI is also failing. I think this is a problem of Neovim nightly and node-host. So I think this PR is mergable. @billyvg, what do you think?
CC: @janlazo
Fixes #47

AppVeyor for Windows CI

---

.gitignore
__tests__/integration/rplugin/node/test/.babelrc.js
__tests__/integration/rplugin/node/test_2/.babelrc.js
package.json
src/api/helpers/createChainableApi.ts
src/host/NvimPlugin.test.ts
src/host/NvimPlugin.ts
src/host/factory.test.ts
src/host/factory.ts
src/index.ts
src/plugin/autocmd.ts
src/plugin/plugin.test.ts
src/plugin/plugin.ts
yarn.lock

Fixes TS builds failing when using plugin decorators.
Released as 4.0.1
Closes #57 
Closes #64

fix: plugin decorator types

---

package.json
yarn.lock

Right now if a plugin installs `neovim`, node_modules gets all the type information, which is not always needed.
Moved `@types` packages to depDeps to only include  hard dependencies during `npm install --production`.

chore(): move types to devdeps

---

src/host/factory.ts

The log level `info` and `debug` contains too much information, the log file could easily increased to 100k lines, this change would makes it easier for plugin author to find error in the log.
Winston tends to ignore more than one error at the same time, so I put the stack log first.

Use logger.error for plugin error

---

src/utils/buffered.ts
src/utils/transport.ts

`msgpack-lite` and `msgpack5` could be quite slow when working with streams that emit small chunks (8kb) of data each time,  it could be solved by using a buffered stream in the middle.
Detail at https://github.com/chemzqm/stream-issue

fix(): slow performance on decode large data

---

scripts/findMissingApi.js

Currently CI is failing at checking missing APIs due to `nvim_buf_(attach|detach)`.
https://travis-ci.org/neovim/node-client/jobs/390613752
I fixed the issue. And I modified the check for non-normalized names to look `name` rather than `methodName` because multiple methods may have the same method name. Checking `name` directly is safer.
Of course I checked these APIs are implemented in a client: https://github.com/neovim/node-client/blob/master/src/api/Buffer.ts#L29-L42

fix(CI): Consider nvim_buf_(attach|detach) APIs

---

src/api/Buffer.test.ts
src/api/client.ts

The buffer notification works well, except that I have to attach same event listener to a specified buffer event in different autocmd callback.
This PR prevents same listener attached multiply times.

feat(api): listen once for same event & handler

---

src/api/Buffer.test.ts
src/api/Buffer.ts

Mark `isAttached` to false on detach.
Note that there is a wait in the test, since attach again without detach returned would take no effect. May be the detach should return a promise to help this case.

fix(api): reattach of buffer sometimes not working

---

src/api/Buffer.test.ts

The way tests were written, they were all using the same buffer.
And since the tests are all asynchronous, there was a good chance
that the input of one test would affect the result of another test.
To make things worse, each test was expecting the buffer to be in
the state the previous test would have left it, which does not
work well with `jest --watch`, or running one test as a standalone.
What I did was to add a wrapper, `withBuffer`, which creates a new
buffer before the test, makes it accessible to the test itself,
and then close it down once the test is done.
Was discovered when doing work for #96

make each test uses its own buffer

---

codecov.yml

- Disable obnoxious comment.
- Allow range. Currently uses the same 70...100 range as neovim. Feel
free to change it to something narrower; the main goal is to avoid
failing PRs for sub-1% fluctuations.
- Fix the badge?

CI: config: codecov.yml

---

__tests__/integration.test.ts
bin/cli.js
package.json
yarn.lock

Fix #46 
I included style changes because of the precommit check with husky.
Running node with `--inspect-brk` silences the following error whether I spawn a new host or not:
```
net.js:704
throw new TypeError(
^
TypeError: Invalid data, chunk must be a string or buffer, not object
at WriteStream.Socket.write (net.js:704:11)
at Transport.parseMessage (/home/janlazo/repo/git/node-client/lib/utils/transport.js:105:31)
at DecodeStream.Transport.decodeStream.on (/home/janlazo/repo/git/node-client/lib/utils/transport.js:37:18)
at emitOne (events.js:116:13)
at DecodeStream.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at DecodeStream.Readable.push (_stream_readable.js:208:10)
at DecodeStream.Transform.push …
```

[RFC] debug: spawn child process with --inspect-brk

---

package.json
src/api/Buffer.test.ts
src/api/Buffer.ts
src/api/client.ts

PR originally by @chemzqm 
* Not use internal isAttached
* Add buffer.isAttached method
* Unbind listener if attach failed
Closes https://github.com/neovim/node-client/pull/93

fix(buffer): fix attach events

---

src/api/Buffer.test.ts
src/api/Buffer.ts
src/api/Neovim.test.ts
src/api/Neovim.ts
src/attach/attach.test.ts

Adds APIs for:
- nvim_create_namespace
- nvim_get_namespaces
- nvim_buf_clear_namespace
- nvim_buf_set_virtual_text
Add deprecation notice for `Buffer.clearHighlight`

feat(api): Add namespace and virtual text API

---

packages/neovim/package.json
packages/neovim/src/utils/transport.ts

This PR attempts to bump up msgpack from `msgpack-lite` to latest official (https://github.com/msgpack/msgpack-javascript).
msgpack-lite has not been updated for amount of time, meanwhile official bindings improved implementation, as well as some experimental perf improvement approach as well like wasm backend (https://github.com/msgpack/msgpack-javascript/blob/c969bc9045a2fc2e70cf3bddd7ccd2e71cff1a78/src/wasmFunctions.ts#L3, still experimental though)
to conform `@msgpack`'s api `transport`'s internal implementation has changed, but does not exposes any breaking changes so far.

feat(transport): bump up msgpack to latest official

---

packages/neovim/src/api/Base.ts
packages/neovim/src/attach/attach.ts
packages/neovim/src/utils/logger.ts

relates to https://github.com/asvetliakov/vscode-neovim/issues/134
current logger only allows customizable behavior via env variable which works for majority of node.js entrypoint, but some cases (like vs code extension) overriding env variable is not very much feasible cases. `NeovimClient` ctor already accepts custom logger, but `attach` does not exposes it - this PR expands signature to `attach` to allow specify options for customizing points. 
Instead of expanding param to directly accepts `logger`, it accepts `options` object instead for possible future customizations.

feat(attach): allow custom logger for attach neovim proc

---

packages/decorators/package.json
packages/neovim/package.json

This repository is tested with LTS versions. And Node.js v8 reached EOL at the end of 2019. I think v10 or later is a good specification for Node.js versions we support currently.
It produces a warning when users try to use this package with wrong version of Node.js. It does not make an error. So, if users really want to use this package with wrong version of Node.js and they understands what they're doing, they can ignore the warning.
Related to #144

Specify Node.js version >=10 in package.json files

---

azure-pipelines.yml

It seems that azure pipeline has stopped support for macOS 10.13. Now only 10.14 and 10.15 are available.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent

Use macOS 10.14 on CI

---

package.json

chore: Bump dev node version to 16.13.1

---

packages/neovim/scripts/nvim.js

Use $NVIM with Nvim 0.8+.
https://github.com/neovim/neovim/pull/11009 (Nvim 0.8+) will change Nvim so that $NVIM_LISTEN_ADDRESS is _not_ passed to child processes.  After that, the correct way to detect a "host" or "parent" Nvim is to check for $NVIM env var: this means the current process is a child of Nvim.
The old $NVIM_LISTEN_ADDRESS env var had conflicting purposes as both a parameter ("the current process should _listen on_ this address") and a descriptor ("the current process is a _child of_ this address").

fix(nvim.js): $NVIM_LISTEN_ADDRESS is deprecated

---

.github/workflows/ci.yml
packages/neovim/src/index.ts
packages/neovim/src/utils/getNvimFromEnv.test.ts
packages/neovim/src/utils/getNvimFromEnv.ts

closes #146 
I'm still working on it.
The version comparison is currently just a placeholder for the correct implementation.
I would appreciate any feedback to know if I'm on the right path here. @justinmk

nvim version from env

---

package.json

"resolutions" was added in 96ed4d35fb25314a7bb9f9aee564cfd38c7aeff1 but is no longer needed because we don't use yarn since 10a3432b9526ae52e03b88d3adf377b95ed723e2 and npm doesn't support "resolutions".

build: remove "resolutions" field

---

packages/neovim/src/api/Buffer.ts
packages/neovim/src/api/Neovim.ts
packages/neovim/src/api/Tabpage.ts
packages/neovim/src/api/Window.ts
packages/neovim/src/api/types.ts

Wrong type but no error
Correct type but has an error

fix: fix types of AsyncWindow/Buffer/Tabpage

---

.gitattributes
.github/workflows/ci.yml
packages/neovim/package.json

Problem:
Lint fails on Windows CI, because git converts text to CRLF and prettier expects LF.
Solution:
Disable git's automatic EOL conversion for text files.

fix(ci): lint on Windows, jest config

---

.github/workflows/ci.yml
.gitignore
codecov.yml
packages/neovim/package.json

Problem:
Error: Codecov token not found. Please provide Codecov token with -t flag.
##[warning]Codecov: Failed to properly create commit: The process
'/Users/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
Solution:
- Add `CODECOV_TOKEN` as an org secret.
- Pass `CODECOV_TOKEN` in the ci spec.

ci: fix codecov

---

.eslintrc.js
README.md
codecov.yml
packages/neovim/src/utils/getNvimFromEnv.test.ts
packages/neovim/src/utils/getNvimFromEnv.ts

- don't export `parseVersion`, `compareVersions`
- rename options
- add test coverage
- remove TypeErrors for conditions which cannot happen (thus aren't testable)

refactor: getNvimFromEnv

---

packages/integration-tests/__tests__/integration.test.ts
packages/neovim/README.md
packages/neovim/scripts/nvim.js
packages/neovim/src/api/Buffer.test.ts
packages/neovim/src/api/Neovim.test.ts
packages/neovim/src/api/Tabpage.test.ts
packages/neovim/src/api/Window.test.ts
packages/neovim/src/attach/attach.test.ts
packages/neovim/src/utils/getNvimFromEnv.test.ts
packages/neovim/src/utils/getNvimFromEnv.ts

Problem:
If a found "nvim" does not meet `minVersion`, it's included in _both_ `matches` and `unmatchedVersions`. It should only be included in `unmatchedVersions`.
Solution:
- If a found "nvim" is broken or does not meet `minVersion`, do not  include it in matches.
- Merge the `unmatchedVersions` and `errors` collections into a single  `invalid` list.

fix: getNvimFromEnv returns invalid Nvim in matches

---

packages/neovim/src/utils/findNvim.ts

fix #319
Note: this wasn't caught in CI because the Nvim path on Windows CI does not have spaces:
"D:\\a\\node-client\\node-client\\nvim-win64\\bin\\nvim.exe"

fix: findNvim() fails if path has spaces

---

CHANGELOG.md
packages/integration-tests/src/factory.test.ts
packages/neovim/bin/cli.js
packages/neovim/src/api/Base.ts
packages/neovim/src/api/client.ts
packages/neovim/src/attach/attach.ts
packages/neovim/src/host/NvimPlugin.test.ts
packages/neovim/src/host/NvimPlugin.ts
packages/neovim/src/host/factory.ts
packages/neovim/src/host/index.ts
packages/neovim/src/plugin/plugin.test.ts
packages/neovim/src/plugin/plugin.ts
packages/neovim/src/testUtil.ts
packages/neovim/src/utils/logger.ts

Problem:
- d9bc2efe30cd4c0de3691e953cace04d02e7855f #138 allows clients to supply a custom logger, but the logger is not always used.
- The winstonLogger is always initialized, even when a custom logger is given.
Solution:
- Update all logging calls to use the custom logger.
- Skip initialization of winstonLogger if a custom logger is given.

fix(logger): use custom logger

---

.eslintrc.js
.github/workflows/ci.yml
CHANGELOG.md
README.md
packages/neovim/src/api/Base.ts
packages/neovim/src/attach/attach.ts
packages/neovim/src/plugin/autocmd.ts
packages/neovim/src/testUtil.ts
packages/neovim/src/utils/logger.ts
packages/neovim/src/utils/util.ts

BEFORE:
info: [object Object]
debug: request -> nvim_command
debug: request -> nvim_list_wins
debug: response -> nvim_command: null
debug: response -> nvim_list_wins: [object Object],[object Object],[object Object],[object Object]
...
AFTER:
2024-03-20 11:37:25 INF {
matches: [
{
nvimVersion: '0.10.0-dev-2657+g9765efb40f57',
path: '/usr/local/bin/nvim',
buildType: 'RelWithDebInfo',
luaJitVersion: '2.1.1710088188'
}
],
invalid: []
}
2024-03-20 11:37:25 DBG request  -> nvim_command
2024-03-20 11:37:25 DBG request  -> nvim_list_wins
2024-03-20 11:37:25 DBG response -> nvim_command: null
2024-03-20 11:37:25 DBG response -> nvim_list_wins: [
{
_events: [Object: null prototype] {},
_eventsCount: 0,
_maxListeners: undefined,
transport: '[Object]',
data: 1003,
logger: '[Object]',
client: …

feat(logger): timestamp, pretty-print objects

---

.github/workflows/ci.yml
README.md
packages/neovim/src/api/client.ts
packages/neovim/src/host/index.ts

refactor(logging): cleanup, use format specifiers

---

packages/decorators/src/plugin/autocmd.ts
packages/decorators/src/plugin/command.ts
packages/decorators/src/plugin/plugin.ts
packages/decorators/src/plugin/types.ts
packages/neovim/src/api/Base.ts
packages/neovim/src/api/Buffer.ts
packages/neovim/src/api/Neovim.test.ts
packages/neovim/src/api/Neovim.ts
packages/neovim/src/api/Tabpage.ts
packages/neovim/src/api/Window.ts
packages/neovim/src/api/client.ts
packages/neovim/src/api/utils/createChainableApi.ts
packages/neovim/src/attach/attach.test.ts
packages/neovim/src/host/NvimPlugin.ts
packages/neovim/src/host/factory.ts
packages/neovim/src/host/index.ts
packages/neovim/src/plugin/autocmd.ts
packages/neovim/src/plugin/command.ts
packages/neovim/src/plugin/plugin.ts
packages/neovim/src/utils/buffered.ts
packages/neovim/src/utils/findNvim.ts
packages/neovim/src/utils/logger.ts
packages/neovim/src/utils/transport.ts
tsconfig.json

- enable `"strict": true` in tsconfig
- fix errors
tsconfig ignores the test files...? https://github.com/neovim/node-client/blob/d3bc8d36b50ccc188e083b33ff537819e661dd88/packages/neovim/tsconfig.json#L7
https://github.com/neovim/node-client/issues/352

build: enforce type checks, fix type errors

---

README.md
package.json

I'm trying to build node-client on nix using buildNpmPackages, as nix is migrating away from the old way of building node packages, and I get the following:
```
error: builder for '/nix/store/yp8wvva7jzd0z1p6myafvc7h6j2baiax-neovim-node-client-5.1.0.drv' failed with exit code 1;
last 25 log lines:
>
>
> > @neovim/integration-tests@4.10.1 build
> > tsc --pretty
>
>
> > @neovim/example-plugin-decorators@4.10.1 build
> > babel src --out-dir lib
>
> Successfully compiled 2 files with Babel (132ms).
> Finished npmBuildHook
> Running phase: installPhase
> Executing npmInstallHook
> npm ERR! Invalid package, must have name and version
```
This seems to be solved simply by adding the name/version into package.json, which this PR does. I've confirmed that the it builds/works correctly with this …

Add name and version to package.json

---

.github/workflows/ci.yml

Problem:
macos CI fails:
Error: Unable to find Node version '14' for platform darwin and architecture arm64.
Solution:
- Skip node 14/16 on macos and windows (to save CI time).
- Add testing for node 20.

ci: add node 20, drop node 14/16 on mac/win

---

CHANGELOG.md
packages/neovim/src/attach/attach.test.ts
packages/neovim/src/utils/logger.ts

Exception when calling `console.assert()`.
Example from https://github.com/vscode-neovim/vscode-neovim/issues/2242 :
{"tag":"dap.send","timestamp":1726115647837,"metadata":{"connectionId":3,"message":{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":false,"body":{"error":{"id":9221,"format":
"Error processing initialize: TypeError: Cannot read properties of undefined (reading 'apply')
at console.<computed> [as assert] (/home/vscode/.vscode-server/extensions/asvetliakov.vscode-neovim-1.18.11/node_modules/neovim/lib/utils/logger.js:72:46)
at r.onInitialize (/vscode/vscode-server/…/extensions/ms-vscode.js-debug/src/extension.js:120:345)
at /vscode/vscode-server/…/extensions/ms-vscode.js-debug/src/extension.js:119:1632
at zc._onMessage …

fix(logger): console.assert() throws exception

---

.github/workflows/ci.yml

Code coverage is not counted for Windows. For example, in https://github.com/neovim/node-client/pull/397 codecov flags the `if (LOCALAPPDATA)` branches.
Run codecov on all platforms (but only for a single node version, to be frugal).

ci: run codecov on all platforms

---

packages/neovim/src/utils/findNvim.test.ts
packages/neovim/src/utils/findNvim.ts

Closes #370 and #267
Introducing a new 'stopOnFirstMatch' option for the findNvim function, which helps reduce the number of system calls when the caller only need one valid match. Additionally, the search now includes common locations where Neovim might be installed.

feat: add firstMatch option for findNvim

---

CHANGELOG.md
packages/neovim/src/attach.ts
packages/neovim/src/host/index.ts
packages/neovim/src/index.ts
packages/neovim/src/testUtil.ts
packages/neovim/src/utils/transport.test.ts
packages/neovim/src/utils/transport.ts

related: https://github.com/vscode-neovim/vscode-neovim/issues/2184

feat(transport): show contents of invalid RPC message in TypeError

---

packages/neovim/src/api/Buffer.test.ts
packages/neovim/tsconfig.json

ref #352
Our linter and TypeScript config disagreed on test files. Linter included them, config didn't.
https://github.com/neovim/node-client/blob/65ddb5e7c8fa6c1bd4a6cd6564ad0cdf83b7e92c/packages/neovim/tsconfig.json#L7
https://github.com/neovim/node-client/blob/65ddb5e7c8fa6c1bd4a6cd6564ad0cdf83b7e92c/package.json#L37
This PR should fix this as well.

build(tests): type check Buffer.test.ts

---

packages/neovim/src/api/Neovim.test.ts
packages/neovim/src/api/Neovim.ts
packages/neovim/src/api/Tabpage.test.ts
packages/neovim/src/api/Window.test.ts
packages/neovim/src/host/NvimPlugin.test.ts
packages/neovim/src/plugin/plugin.test.ts
packages/neovim/tsconfig.json

build(tests): type check packages/neovim/*.test.ts

---

packages/integration-tests/__tests__/integration.test.ts
packages/integration-tests/package.json
packages/integration-tests/tsconfig.json

build(tests): type check integration.test.ts

---

packages/neovim/src/attach/attach.test.ts

Closes #314.
Not sure if this is a good improvement, any suggestions? @justinmk

test(attach): improve disconnect test

---

.eslintrc.js
.github/workflows/ci.yml
package-lock.json
package.json
packages/integration-tests/__tests__/integration.test.ts
packages/integration-tests/package.json
packages/integration-tests/src/factory.test.ts
packages/integration-tests/tsconfig.json
packages/neovim/.mocharc.js
packages/neovim/package.json
packages/neovim/src/api/Buffer.test.ts
packages/neovim/src/api/Neovim.test.ts
packages/neovim/src/api/Tabpage.test.ts
packages/neovim/src/api/Window.test.ts
packages/neovim/src/attach/attach.test.ts
packages/neovim/src/host/NvimPlugin.test.ts
packages/neovim/src/plugin/plugin.test.ts
packages/neovim/src/testSetup.ts
packages/neovim/src/testUtil.ts
packages/neovim/src/utils/findNvim.test.ts
packages/neovim/src/utils/findNvim.ts
packages/neovim/src/utils/transport.test.ts
packages/neovim/src/utils/transport.ts
packages/neovim/tsconfig.json
tsconfig.json

Closes #333.
To make a transition from Jest feasible. Capabilities Jest offers that we might need to keep:
Expect is a standalone npm package.
The jest.fn(), jest.spyOn() is provided by jest-mock, we can just use this package directly.

test: replace jest with mocha

---

.prettierrc.json
packages/decorators/src/plugin/autocmd.ts
packages/decorators/src/plugin/plugin.ts
packages/integration-tests/src/factory.test.ts
packages/neovim/src/api/Base.ts
packages/neovim/src/api/Buffer.test.ts
packages/neovim/src/api/Buffer.ts
packages/neovim/src/api/Neovim.test.ts
packages/neovim/src/api/Neovim.ts
packages/neovim/src/api/Window.ts
packages/neovim/src/api/client.ts
packages/neovim/src/api/utils/createChainableApi.ts
packages/neovim/src/attach/attach.test.ts
packages/neovim/src/attach/attach.ts
packages/neovim/src/host/NvimPlugin.test.ts
packages/neovim/src/host/NvimPlugin.ts
packages/neovim/src/host/factory.ts
packages/neovim/src/host/index.ts
packages/neovim/src/plugin/plugin.test.ts
packages/neovim/src/plugin/plugin.ts
packages/neovim/src/testUtil.ts
packages/neovim/src/types/VimValue.ts
packages/neovim/src/utils/findNvim.test.ts
packages/neovim/src/utils/findNvim.ts
packages/neovim/src/utils/logger.ts
packages/neovim/src/utils/transport.ts
packages/neovim/src/utils/util.ts

Since `.editorconfig` was added, eslint (or prettier) seems to treat it as authoritative. So let's just increase the line length.

lint: increased line-length

---

package-lock.json
packages/integration-tests/package.json

The following error was reported by eslint:
```sh
❯ npm run lint
...
/Users/mikavilpas/git/neovim-node-client/packages/integration-tests/src/factory.test.ts:1:62: Unable to resolve path to module 'neovim'. [Error/import/no-unresolved]
1 problem
```

chore: fix eslint error about missing neovim pkg in integration-tests

---

.babelrc.js
.eslintrc.js
.github/dependabot.yml
.github/workflows/ci.yml
.prettierrc.json
README.md
examples/README.md
examples/class.md
examples/decorators.md
examples/functional.md
examples/prototype.md
examples/rplugin/node/nvim-example/index.js
packages/example-plugin-decorators/src/index.js
packages/integration-tests/__tests__/integration.test.ts
packages/neovim/.mocharc.js
packages/neovim/bin/cli.js
packages/neovim/bin/generate-typescript-interfaces.js
packages/neovim/scripts/findMissingApi.js

Issue
=====
The prettier parser was set to `typescript` in the `.prettierrc.json` file. Because prettier was used for multiple files types, it caused errors when formatting files that were not TypeScript.
Here is an example:
```sh
README.md
[error] README.md: SyntaxError: Invalid character. (1:1)
[error] > 1 | # Neovim node.js client
[error]     | ^
[error]   2 |
[error]   3 | | CI (node >= 14, Linux/macOS/Windows) | Coverage | npm |
[error]   4 | |----------------------------|----------|-----|
```
This seems to cause the build to fail as of the most recent commit https://github.com/neovim/node-client/commit/74880148636620f3f76e0a568aed10ce18b512a1
Solution
========
Automatically infer the parser based on the file extension.
References:
- …

build: infer prettier parser from file extension

---

.eslintrc.js
.prettierignore
package-lock.json
package.json
packages/decorators/src/plugin/plugin.ts
packages/neovim/src/api/Neovim.ts
packages/neovim/src/api/utils/createChainableApi.ts
packages/neovim/src/host/NvimPlugin.ts
packages/neovim/src/plugin/autocmd.ts
packages/neovim/src/plugin/function.ts
packages/neovim/src/types/Spec.ts

- `npm run lint` now checks formatting with prettier and eslint as discussed in #445 
- `npm run fixlint` now fixes formatting with `prettier --write` and `eslint --fix`
- lint-staged also uses `npm run fixlint` to keep things consistent
- ci seems to already check formatting with prettier and eslint
- added jsdoc type hints to the eslintrc.js file for autocompletion
Eslint now uses a blocklist instead of allowlist for ignoring files. It might be easier to not
accidentally ignore any new files with this approach.
Solves #445

Use prettier for formatting instead of eslint

---

.github/workflows/ci.yml
.prettierignore

see https://github.com/neovim/neovim/pull/32194

ci: neovim nightly name was changed

---

packages/neovim/src/api/client.ts
packages/neovim/src/utils/transport.test.ts
packages/neovim/src/utils/transport.ts
packages/neovim/src/utils/util.ts

Add method to close transport and writer.
Before there was no public way to close the transport/reader/writer created by attach for a socket, and the connection would hold the node process open.
For example, this script would not exit (without an explicit process.exit(0))
```
attach({ socket: pathToNvimSocket })
```
This change adds .close to transport and NeovimClient which ends the writer. The other side of the connection should then close the reader which triggers detach and the cleanup code.
I added asyncDispose methods for folks using modern javascript runtimes that support explicit resource management:
```
await using client = attach({ socket: pathToNvimSocket })
```
Other wise you can call close
```
try {
const client = attach({ socket: pathToNvimSocket })
} finally {
await …
```

feat: add public close methods
